name: evn-gpu
dependencies:
    - python==3.9
    - numpy==1.23.4 
    - matplotlib==3.6.2
    - jupyterlab==3.5.0
    - opencv3
    - Pillow==9.3.0
    - scikit-learn==1.1.3
    - scikit-image
    - scipy==1.9.3
    - h5py==3.7.0
    - eventlet==0.33.1
    - python-socketio==1.8.0
    - python-engineio==2.0.0
    - seaborn
    - pandas==1.5.1
    - keras==2.10.0
    - tensorflow==2.10.0
